#!/bin/bash
# Script para facilitar o upload das imagens para o Cloudinary
# Execute este script na pasta raiz do projeto

echo "🎯 GUIA DE UPLOAD - ESCOLA ILDA VIEIRA VILELA"
echo "============================================="
echo ""
echo "📁 IMAGENS ENCONTRADAS NA PASTA 'imagens/':"
echo ""

# Lista as imagens atuais
ls -la imagens/ | grep -E '\.(jpg|jpeg|png|webp)$' | awk '{print "   " $9}'

echo ""
echo "🔄 MAPEAMENTO PARA CLOUDINARY:"
echo "==============================="
echo ""
echo "ARQUIVO LOCAL                              → PUBLIC ID NO CLOUDINARY"
echo "────────────────────────────────────────────────────────────────────────"
echo "corredor erro.webp                        → ildavieira/corredor-estudantes"
echo "IMG_5465.jpg                              → ildavieira/escola-fachada-principal"
echo "IMG_5482.jpg                              → ildavieira/patio-recreio-escola"
echo "IMG_5487.jpg                              → ildavieira/quadra-esportiva-coberta"
echo "Labfarm.webp                              → ildavieira/laboratorio-farmacia"
echo "patio erro 2.png                          → ildavieira/patio-recreio-escola-2"
echo "patio erro.png                            → ildavieira/patio-recreio-escola-3"
echo "quadra erro 2.png                        → ildavieira/quadra-esportiva-coberta-2"
echo "quadra erro.png                          → ildavieira/quadra-esportiva-coberta-3"
echo "refeitorio erro.webp                     → ildavieira/refeitorio-estudantes"
echo "refeitorio erroo.webp                    → ildavieira/refeitorio-estudantes-2"
echo "sala laboratorio erro.png               → ildavieira/laboratorio-ciencias"
echo "WhatsApp Image 2025-10-28 at 8.36.17 AM.jpeg → ildavieira/sala-leitura-biblioteca"
echo "WhatsApp Image 2025-10-28 at 8.36.18 AM (1).jpeg → ildavieira/biblioteca-estudantes"
echo "WhatsApp Image 2025-10-28 at 8.36.18 AM (2).jpeg → ildavieira/sala-informatica"
echo "WhatsApp Image 2025-10-28 at 8.36.18 AM (3).jpeg → ildavieira/laboratorio-quimica"
echo "WhatsApp Image 2025-10-28 at 8.36.18 AM (4).jpeg → ildavieira/auditorio-escola"
echo "WhatsApp Image 2025-10-28 at 8.36.18 AM.jpeg → ildavieira/secretaria-escola"
echo "WhatsApp Image 2025-10-28 at 8.36.19 AM (1).jpeg → ildavieira/entrada-principal"
echo "WhatsApp Image 2025-10-28 at 8.36.19 AM (2).jpeg → ildavieira/sala-aula-1"
echo "WhatsApp Image 2025-10-28 at 8.36.19 AM.jpeg → ildavieira/diretoria-escola"
echo ""
echo "🎯 IMAGEM PRINCIPAL PARA BANNER:"
echo "IMG_5465.jpg → ildavieira/hero-banner"
echo ""
echo "🔗 PRÓXIMOS PASSOS:"
echo "1. Acesse: https://cloudinary.com/console"
echo "2. Vá em 'Media Library' → 'Upload'"
echo "3. Para cada imagem, use o Public ID correspondente da tabela acima"
echo "4. Após upload, execute: npm run dev"
echo "5. Verifique se as imagens aparecem no site"
echo ""
echo "📋 PARA VERIFICAR DEPOIS DO UPLOAD:"
echo "As imagens devem aparecer nas seguintes páginas:"
echo "- Página inicial: Banner hero"
echo "- Nossa Escola: Galeria de infraestrutura"
echo "- Todas as páginas: Layout responsivo"
echo ""